### ISSUE TITLE
Hibernate/Unit Testing

### ISSUE THREAD

**Issue by redfoxanna** [redfoxanna/diamond-poems#8]
Hi @pawaitemadisoncollege, I reconfigured Diamond Poems so that I have a many-to-many relationship between Poem and Genre. I followed the videos you have for hibernate many-to-many relationships and created a new PoemGenre entity to represent that relationship-- similar to your OrderProduct example in the video.

My issue is now that I go back and run my unit tests, they are failing. I am getting null for database.connection [seen here](https://github.com/redfoxanna/diamond-poems/blob/main/screenshots/unit-test-failure.png). For the life of me I can't debug this. I've checked that the properties for the database were being loaded correctly (they are), I have checked over my hibernate.cfg.xml and am now out of ideas. 

The strange part is, the insertSuccess() test is working just fine? 

Is there something I missed when mapping out the relationship between Poem, Genre and PoemGenre? Or is this more likely a configuration issue?

**Comment by pawaitemadisoncollege** [comment]
Hi @redfoxanna!

This is an interesting one! Here are some things I noticed/wonder:

- The screenshot shows a class in the jaxb package. This isn't a class you wrote, so I'm curious where in the execution this is getting called. I suspect the real problem happens earlier than this - either in the Database class when things are reset or in the dao/hibernate calls.
- It's interesting that the insert works. I'm curious if it is always the first test that passes and the rest fail? If you run a single test, does that pass regardless of which one it is (delete, update, getall...)?
- Does the cleandb.sql run ok outside of the tests (execute it on the database in the IntelliJ db console)?
- Any chance the time zone issue is causing this?

**Comment by redfoxanna** [comment]
Hi @pawaitemadisoncollege! 

* The insert is always working/passing and is indeed the last test to run.
* If I run a single test, it fails unless it's the insert()
* My cleanDB.sql runs ok outside of the tests when I open a console and run the sql dump code
* I've attached a couple more screenshots on the specific errors I'm getting-- they seem to be on the [getById](https://github.com/redfoxanna/diamond-poems/blob/main/screenshots/get-by-id-failure.png) and [getAll](https://github.com/redfoxanna/diamond-poems/blob/main/screenshots/get-all-failure.png)

Looking at Google and some of the errors I'm seeing from the screenshots, it might have something to do with tables being lazy loading of associated entities. I am wondering if the collections in my entities need to have a fetchType=EAGER?

Could this be a time zone issue? I thought I fixed that but now am remembering that you said we might have to run those commands every so often unless we go into the config file for mysql and change the time setting. I will try that and see if that does anything!

**Comment by pawaitemadisoncollege** [comment]
Yes! Eager is likely the key here! Let me know if that does it!

**Comment by redfoxanna** [comment]
Hi @pawaitemadisoncollege, I have passing unit tests! I went back to a version of my code from many week ago where I knew the tests were all passing. From there I had to add: 
```
@OneToMany(mappedBy = "poem", fetch = FetchType.EAGER, cascade = CascadeType.REMOVE)
private Set<PoemGenre> genres = new HashSet<>();
```

I also updated `.equals()` and `.hashcode()` to include the collections and now the tests have ran a few times with no issues! 

Thanks for your help! :-)

**Comment by pawaitemadisoncollege** [comment]
Awesome!!! I think I mentioned "eager" in week 5, but obviously need to emphasize that more!!! Glad you got it working!
